import * as glob from "fast-glob";

export const getWorkflowsPaths = () => {
    const workflowFilesGlobs = [[process.cwd(), ".github", "workflows", "**/*.wac.ts"].join("/")];

    return glob.sync(workflowFilesGlobs, { onlyFiles: true });
};

export const clearImportCache = () => {
    // For the "watch" command, we need to flush the cached imported files. Otherwise, once imported, the
    // above dynamic imports will always just returned cached imported objects and no change will happen.
    Object.keys(require.cache).forEach(function (key) {
        delete require.cache[key];
    });
};

export const TOP_YAML_WORKFLOW_COMMENT = [
    "# This file was automatically generated by github-actions-wac.",
    "# DO NOT MODIFY IT BY HAND. Instead, modify the source *.wac.ts file(s)",
    '# and run "github-actions-wac build" (or "ghawac build") to regenerate this file.',
    '# For more information, run "github-actions-wac --help".'
].join("\n");
