import glob from "fast-glob";

export const getWorkflowsPaths = () => {
    const workflowFilesGlobs = [[process.cwd(), ".github", "workflows", "**/*.wac.ts"].join("/")];

    return glob.sync(workflowFilesGlobs, { onlyFiles: true });
};

export const TOP_YAML_WORKFLOW_COMMENT = [
    "# This file was automatically generated by github-actions-wac.",
    "# DO NOT MODIFY IT BY HAND. Instead, modify the source *.wac.ts file(s)",
    '# and run "github-actions-wac build" (or "ghawac build") to regenerate this file.',
    '# For more information, run "github-actions-wac --help".'
].join("\n");
